### ISSUE TITLE
A formula problem in sheen model by patry

### ISSUE THREAD

**Issue by zoujiahuan** [tizian/ltc-sheen#1]
According to the slides from "Samurai Shading in Ghost of Tsushima"
[https://blog.selfshadow.com/publications/s2020-shading-course/patry/s2020_pbs_patry_slides.pdf](https://blog.selfshadow.com/publications/s2020-shading-course/patry/s2020_pbs_patry_slides.pdf),
on page 52 , it can be seen that the denominator for the exponent part of e is  udotv * vdotn.

While in `sheenbaselines.cpp`, class SheenPatry :
```
Float tmp1           = CosTheta(wo + wi),
      tmp2           = tmp1 / (cosThetaI * cosThetaO),
      numerator      = 1.f - std::exp(-density * tmp2);
```
the denominator here I suppose is equivalent to udotn * vdotn?
Is this a mistake here? If not, what's the reason?

As I am not familiar with pbrt, please forgive and correct me if I make any mistakes.

Thanks!

**Comment by tizian** [comment]
Hi!
I suspect that the "Samurai Shading" slides actually have a typo in that denominator---though I could be wrong!
I got the `dot(u, n) * dot(v, n)` expression from the original paper mentioned on that slide (Koenderink and Pont 2002 Eq. 8). This seems to make more sense to me as the BSDF would otherwise not even be reciprocal.

**Comment by zoujiahuan** [comment]
Hi tizian,

Thanks for your reply. I checked the original paper and like you said, it might be a typo. 

Another thing is that I run `sphere.pbrt`, with paramters `"string type" ["conty_kulla"]` and `Rotate 0`.
However, the rendered result is not like what you quoted in your paper.
This is what I get:

![conty_kulla_sphere](https://user-images.githubusercontent.com/23361412/190167957-4034f354-1ec5-4013-86b8-9a406f735827.png)

The image of `(d) [Conty and Kulla]` in your paper is more like the rendered result of `patry` at least in my machine.

Could you help to check the reason? Thank you!

**Comment by tizian** [comment]
What roughness parameter do you use? That image you posted here looks a lot like the Conty-Kulla model at a very high roughness.

**Comment by tizian** [comment]
Did you also take a look at the [supplemental material](https://tizianzeltner.com/projects/Zeltner2022Practical/supplemental.pdf)? There we have comparisons using a range of roughness values.

**Comment by zoujiahuan** [comment]
Oh I see, I just use the default roughness value 0.5 in sphere.pbrt.
Thanks for letting me know the supplemental materials! Sorry I didn't notice that.
So what roughness value you used for the image in your paper?

**Comment by tizian** [comment]
From checking my scripts it should be `alpha = 0.05` and `Csheen = 0.5`. These parameters were chosen manually in order to roughly match the explicit fiber case at perpendicular incidence.

**Comment by zoujiahuan** [comment]
Thanks for your patient answer! I will close this issue.

**Comment by tizian** [comment]
Sure, no worries!
I'll add a comment in the code about the original question to avoid future confusion for others and myself :)
